# Generated by Django 5.1.3 on 2025-01-16 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_patienthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientHistory',
            new_name='HeartPatientHistory',
        ),
    ]
